export const FRENCH_TO_ENGLISH: Record<string, string> = {
  'Algerie': 'Algeria',
  'Danemark': 'Denmark',
  'Egypte': 'Egypt',
  'Afrique du Sud': 'South Africa',
  'Allemagne': 'Germany',
  'Arabie Saoudite': 'Saudi Arabia',
  'Argentine': 'Argentina',
  'Australie': 'Australia',
  'Autriche': 'Austria',
  'Belgique': 'Belgium',
  'Bresil': 'Brazil',
  'Canada': 'Canada',
  'Chili': 'Chile',
  'Chine': 'China',
  'Colombie': 'Colombia',
  'Coree du Sud': 'South Korea',
  'Costa Rica': 'Costa Rica',
  'Croatie': 'Croatia',
  'Cuba': 'Cuba',
  'Espagne': 'Spain',
  'Etats-Unis': 'United States',
  'Ethiopie': 'Ethiopia',
  'Finlande': 'Finland',
  'France': 'France',
  'Grece': 'Greece',
  'Hongrie': 'Hungary',
  'Inde': 'India',
  'Indonesie': 'Indonesia',
  'Irlande': 'Ireland',
  'Italie': 'Italy',
  'Japon': 'Japan',
  'Kazakhstan': 'Kazakhstan',
  'Kenya': 'Kenya',
  'Koweit': 'Kuwait',
  'Malaysie': 'Malaysia',
  'Maroc': 'Morocco',
  'Mexique': 'Mexico',
  'Moldavie': 'Moldova',
  'Mongolie': 'Mongolia',
  'Mozambique': 'Mozambique',
  'Myanmar': 'Myanmar',
  'Nigeria': 'Nigeria',
  'Norvege': 'Norway',
  'Nouvelle-Zelande': 'New Zealand',
  'Pakistan': 'Pakistan',
  'Pays-Bas': 'Netherlands',
  'Perou': 'Peru',
  'Philippines': 'Philippines',
  'Pologne': 'Poland',
  'Portugal': 'Portugal',
  'Roumanie': 'Romania',
  'Royaume-Uni': 'United Kingdom',
  'Russie': 'Russia',
  'Senegal': 'Senegal',
  'Serbie': 'Serbia',
  'Singapour': 'Singapore',
  'Slovaquie': 'Slovakia',
  'Slovenie': 'Slovenia',
  'Somalie': 'Somalia',
  'Soudan': 'Sudan',
  'Sri Lanka': 'Sri Lanka',
  'Suede': 'Sweden',
  'Suisse': 'Switzerland',
  'Suriname': 'Suriname',
  'Taiwan': 'Taiwan',
  'Tanzanie': 'Tanzania',
  'Tchad': 'Chad',
  'Thailande': 'Thailand',
  'Togo': 'Togo',
  'Trinite-et-Tobago': 'Trinidad and Tobago',
  'Tunisie': 'Tunisia',
  'Turquie': 'Turkey',
  'Ukraine': 'Ukraine',
  'Uruguay': 'Uruguay',
  'Venezuela': 'Venezuela',
  'Vietnam': 'Vietnam',
  'Yemen': 'Yemen',
  'Zambie': 'Zambia',
  'Zimbabwe': 'Zimbabwe',
};
