// Mapping français → anglais pour normaliser les noms de pays
const FRENCH_TO_ENGLISH: Record<string, string> = {
  'Afrique du Sud': 'South Africa',
  'Albanie':'Albania',
  'Algérie': 'Algeria',
  'Allemagne': 'Germany',
  'Andorre': 'Andorra',
  'Arabie Saoudite': 'Saudi Arabia',
  'Argentine': 'Argentina',
  'Arménie': 'Armenia',
  'Australie': 'Australia',
  'Autriche': 'Austria',
  'Azerbaïdjan': 'Azerbaijan',
  'Bahamas': 'Bahamas',
  'Bahreïn': 'Bahrain',
  'Bangladesh': 'Bangladesh',
  'Barbade': 'Barbados',
  'Belgique': 'Belgium',
  'Belize': 'Belize',
  'Bénin': 'Benin',
  'Birmanie': 'Myanmar',
  'Bhoutan': 'Bhutan',
  'Biélorussie': 'Belarus',
  'Birmanie-Myanmar': 'Myanmar',
  'Bolivie': 'Bolivia',
  'Bosnie-Herzégovine': 'Bosnia and Herzegovina',
  'Botswana': 'Botswana',
  'Brésil': 'Brazil',
  'Brunei': 'Brunei',
  'Bulgarie': 'Bulgaria',
  'Burkina Faso': 'Burkina Faso',
  'Burundi': 'Burundi',
  'Cambodge': 'Cambodia',
  'Cameroun': 'Cameroon',
  'Canada': 'Canada',
  'Cap-Vert': 'Cabo Verde',
  'Chili': 'Chile',
  'Chine': 'China',
  'Chypre': 'Cyprus',
  'Colombie': 'Colombia',
  'Comores': 'Comoros',
  'Congo': 'Republic of the Congo',
  'Corée du Nord': 'North Korea',
  'Corée du Sud': 'South Korea',
  'Costa Rica': 'Costa Rica',
  'Côte d\'Ivoire': 'Cote d\'Ivoire',
  'Croatie': 'Croatia',
  'Cuba': 'Cuba',
  'Curaçao': 'Curacao',
  'D.R. Congo': 'Democratic Republic of the Congo',
  'Danemark': 'Denmark',
  'Djibouti': 'Djibouti',
  'Dominique': 'Dominica',
  'Égypte': 'Egypt',
  'Émirats Arabes Unis': 'United Arab Emirates',
  'Équateur': 'Ecuador',
  'Érythrée': 'Eritrea',
  'Espagne': 'Spain',
  'Estonie': 'Estonia',
  'États-Unis': 'United States',
  'Éthiopie': 'Ethiopia',
  'Fidji': 'Fiji',
  'Finlande': 'Finland',
  'France': 'France',
  'Gabon': 'Gabon',
  'Gambie': 'Gambia',
  'Géorgie': 'Georgia',
  'Ghana': 'Ghana',
  'Gibraltar': 'Gibraltar',
  'Grèce': 'Greece',
  'Grenade': 'Grenada',
  'Groenland': 'Greenland',
  'Guadeloupe': 'Guadeloupe',
  'Guam': 'Guam',
  'Guatemala': 'Guatemala',
  'Guernesey': 'Guernsey',
  'Guinée': 'Guinea',
  'Guinée équatoriale': 'Equatorial Guinea',
  'Guinée-Bissau': 'Guinea-Bissau',
  'Guyana': 'Guyana',
  'Guyane': 'Guyana',
  'Guyane française': 'French Guiana',
  'Haïti': 'Haiti',
  'Honduras': 'Honduras',
  'Hong Kong': 'Hong Kong',
  'Hongrie': 'Hungary',
  'Île Bouvet': 'Bouvet Island',
  'Île Christmas': 'Christmas Island',
  'Île Norfolk': 'Norfolk Island',
  'Îles Åland': 'Aland Islands',
  'Îles Caïmans': 'Cayman Islands',
  'Îles Cocos': 'Cocos Islands',
  'Îles Féroé': 'Faroe Islands',
  'Îles Heard et McDonald': 'Heard Island and McDonald Islands',
  'Îles Malouines': 'Falkland Islands',
  'Îles Mariannes du Nord': 'Northern Mariana Islands',
  'Îles Marshall': 'Marshall Islands',
  'Îles Salomon': 'Solomon Islands',
  'Îles Turques et Caïques': 'Turks and Caicos Islands',
  'Îles Vierges': 'Virgin Islands',
  'Inde': 'India',
  'Indonésie': 'Indonesia',
  'Irak': 'Iraq',
  'Iran': 'Iran',
  'Irlande': 'Ireland',
  'Islande': 'Iceland',
  'Israël': 'Israel',
  'Italie': 'Italy',
  'Jamaïque': 'Jamaica',
  'Japon': 'Japan',
  'Jersey': 'Jersey',
  'Jordanie': 'Jordan',
  'Kazakhstan': 'Kazakhstan',
  'Kenya': 'Kenya',
  'République Kirghize': 'Kyrgyzstan',
  'Kiribati': 'Kiribati',
  'Koweït': 'Kuwait',
  'Laos': 'Laos',
  'Lesotho': 'Lesotho',
  'Lettonie': 'Latvia',
  'Liban': 'Lebanon',
  'Liberia': 'Liberia',
  'Libye': 'Libya',
  'Liechtenstein': 'Liechtenstein',
  'Lituanie': 'Lithuania',
  'Luxembourg': 'Luxembourg',
  'Macao': 'Macao',
  'Macédoine': 'Macedonia',
  'Macédoine du Nord': 'North Macedonia',
  'Madère': 'Madeira',
  'Madagascar': 'Madagascar',
  'Malaisie': 'Malaysia',
  'Malawi': 'Malawi',
  'Maldives': 'Maldives',
  'Mali': 'Mali',
  'Malte': 'Malta',
  'Mariannes': 'Northern Mariana Islands',
  'Maroc': 'Morocco',
  'Martinique': 'Martinique',
  'Mauritanie': 'Mauritania',
  'Maurice': 'Mauritius',
  'Mayotte': 'Mayotte',
  'Mexique': 'Mexico',
  'Micronésie': 'Micronesia',
  'La Moldavie': 'Moldova',
  'Moïse': 'Maldives',
  'Monaco': 'Monaco',
  'Mongolie': 'Mongolia',
  'Monténégro': 'Montenegro',
  'Montserrat': 'Montserrat',
  'Mozambique': 'Mozambique',
  'Myanmar': 'Myanmar',
  'Namibie': 'Namibia',
  'Nauru': 'Nauru',
  'Népal': 'Nepal',
  'Nicaragua': 'Nicaragua',
  'Nigéria': 'Nigeria',
  'Niger': 'Niger',
  'Niue': 'Niue',
  'Norvège': 'Norway',
  'Nouvelle-Calédonie': 'New Caledonia',
  'Nouvelle-Zélande': 'New Zealand',
  'Oman': 'Oman',
  'Ouganda': 'Uganda',
  'Ouzbékistan': 'Uzbekistan',
  'Pakistan': 'Pakistan',
  'Palaos': 'Palau',
  'Palestine': 'Palestine',
  'Panama': 'Panama',
  'Papouasie-Nouvelle-Guinée': 'Papua New Guinea',
  'Paraguay': 'Paraguay',
  'Pays-Bas': 'Netherlands',
  'Pérou': 'Peru',
  'Perú': 'Peru',
  'Philippines': 'Philippines',
  'Pologne': 'Poland',
  'Polynésie française': 'French Polynesia',
  'Porto Rico': 'Puerto Rico',
  'Portugal': 'Portugal',
  'Qatar': 'Qatar',
  'République Centrafricaine': 'Central African Republic',
  'République Démocratique du Congo': 'Democratic Republic of the Congo',
  'République Dominicaine': 'Dominican Republic',
  'République Tchèque': 'Czech Republic',
  'Rép. Centrafricaine': 'Central African Republic',
  'Rép. Dominicaine': 'Dominican Republic',
  'Réunion': 'Reunion',
  'Roumanie': 'Romania',
  'Royaume-Uni': 'United Kingdom',
  'Russie': 'Russia',
  'Rwanda': 'Rwanda',
  'Sahara occidental': 'Western Sahara',
  'Saint-Barthélemy': 'Saint Barthélemy',
  'Saint-Marin': 'San Marino',
  'Saint-Martin': 'Saint Martin',
  'Saint-Pierre-et-Miquelon': 'Saint Pierre and Miquelon',
  'Saint-Vincent-et-les-Grenadines': 'Saint Vincent and the Grenadines',
  'Sainte-Hélène': 'Saint Helena',
  'Sainte-Lucie': 'Saint Lucia',
  'Salvador': 'El Salvador',
  'Samoa': 'Samoa',
  'Samoa américaines': 'American Samoa',
  'Samoa occidentales': 'Samoa',
  'Sao Tomé-et-Principe': 'Sao Tome and Principe',
  'Sénégal': 'Senegal',
  'Serbie': 'Serbia',
  'Seychelles': 'Seychelles',
  'Sierra Leone': 'Sierra Leone',
  'Singapour': 'Singapore',
  'Sint Maarten': 'Sint Maarten',
  'Slovaquie': 'Slovakia',
  'Slovénie': 'Slovenia',
  'Somalie': 'Somalia',
  'Soudan': 'Sudan',
  'Soudan du Sud': 'South Sudan',
  'Sri Lanka': 'Sri Lanka',
  'Suède': 'Sweden',
  'Suisse': 'Switzerland',
  'Suriname': 'Suriname',
  'Swaziland': 'Swaziland',
  'Syrie': 'Syrian Arab Republic',
  'Tadjikistan': 'Tajikistan',
  'Taïwan': 'Taiwan',
  'Tanzanie': 'Tanzania',
  'Tchad': 'Chad',
  'Terres australes françaises': 'French Southern Territories',
  'Territoire britannique de l\'océan Indien': 'British Indian Ocean Territory',
  'Thaïlande': 'Thailand',
  'Timor oriental': 'Timor-Leste',
  'Timor-Leste': 'Timor-Leste',
  'Togo': 'Togo',
  'Tokelau': 'Tokelau',
  'Tonga': 'Tonga',
  'Trinité-et-Tobago': 'Trinidad and Tobago',
  'Tunisie': 'Tunisia',
  'Turkménistan': 'Turkmenistan',
  'Turquie': 'Turkey',
  'Tuvalu': 'Tuvalu',
  'Ukraine': 'Ukraine',
  'Uruguay': 'Uruguay',
  'USA': 'United States',
  'Vanuatu': 'Vanuatu',
  'Vatican': 'Vatican City',
  'Venezuela': 'Venezuela',
  'Viet Nam': 'Vietnam',
  'Vietnam': 'Vietnam',
  'Yémen': 'Yemen',
  'Zambie': 'Zambia',
  'Zimbabwe': 'Zimbabwe',
};

// Mapping des noms de pays vers les noms de fichiers de drapeaux
const COUNTRY_FLAG_MAP: Record<string, string> = {
  'Afghanistan': 'afghanistan-128x128-32928.png',
  'Albania': 'albanie-128x128-32909.png',
  'Algeria': 'algérie-128x128-32972.png',
  'American Samoa': 'american-128x128-32917.png',
  'Andorra': 'andorre-128x128-32921.png',
  'Angola': 'angola-128x128-32914.png',
  'Anguilla': 'anguilla-128x128-32924.png',
  'Antigua and Barbuda': 'antigua-128x128-32910.png',
  'Argentina': 'argentine-128x128-32919.png',
  'Armenia': 'armenie-128x128-32925.png',
  'Aruba': 'aruba-128x128-32923.png',
  'Australia': 'australie-128x128-32912.png',
  'Austria': 'autriche-128x128-32920.png',
  'Azerbaijan': 'azerbaidjan-128x128-32926.png',
  'Bahamas': 'bahamas-128x128-32915.png',
  'Bahrain': 'bahrein-128x128-32974.png',
  'Bangladesh': 'bangladesh-128x128-32916.png',
  'Barbados': 'barbade-128x128-32913.png',
  'Belarus': 'bielorussie-128x128-32918.png',
  'Belgium': 'belgique-128x128-32911.png',
  'Belize': 'belize-128x128-32927.png',
  'Benin': 'benin-128x128-32922.png',
  'Bermuda': 'bermudes-128x128-32929.png',
  'Bhutan': 'bhoutan-128x128-32931.png',
  'Bolivia': 'bolivie-128x128-32945.png',
  'Bosnia and Herzegovina': 'bosnie-herzegovine-128x128-32932.png',
  'Botswana': 'botswana-128x128-32933.png',
  'Brazil': 'bresil-128x128-32937.png',
  'Brunei': 'brunei-128x128-32944.png',
  'Bulgaria': 'bulgarie-128x128-32973.png',
  'Burkina Faso': 'burkina-faso-128x128-32934.png',
  'Burundi': 'burundi-128x128-32935.png',
  'Cabo Verde': 'cap-vert-128x128-32941.png',
  'Cambodia': 'cambodge-128x128-32978.png',
  'Cameroon': 'cameroun-128x128-32936.png',
  'Canada': 'canada-128x128-32938.png',
  'Cayman Islands': 'iles-cayman-128x128-32986.png',
  'Central African Republic': 'rep-centrafricaine-128x128-32940.png',
  'Chad': 'tchad-128x128-32985.png',
  'Chile': 'chili-128x128-32939.png',
  'China': 'chine-128x128-32942.png',
  'Colombia': 'colombie-128x128-32946.png',
  'Comoros': 'comores-128x128-32981.png',
  'Costa Rica': 'costa-rica-128x128-32948.png',
  'Cote d\'Ivoire': 'cote-divoire-128x128-32949.png',
  'Croatia': 'croatie-128x128-32995.png',
  'Cuba': 'cuba-128x128-32951.png',
  'Curacao': 'curacao-128x128-32950.png',
  'Cyprus': 'chypre-128x128-32953.png',
  'Czech Republic': 'rep-tcheque-128x128-32956.png',
  'Democratic Republic of the Congo': 'congo-kinshasa-128x128-32952.png',
  'Denmark': 'danemark-128x128-32955.png',
  'Djibouti': 'djibouti-128x128-32957.png',
  'Dominica': 'dominique-128x128-32960.png',
  'Dominican Republic': 'rep-dominicaine-128x128-32993.png',
  'Ecuador': 'equateur-128x128-32962.png',
  'Egypt': 'egypte-128x128-32961.png',
  'El Salvador': 'el-salvador-128x128-33011.png',
  'Equatorial Guinea': 'guinee-equatoriale-128x128-32971.png',
  'Eritrea': 'erythree-128x128-32964.png',
  'Estonia': 'estonie-128x128-32959.png',
  'Ethiopia': 'ethiopie-128x128-32958.png',
  'Fiji': 'fidji-128x128-32970.png',
  'Finland': 'finlande-128x128-32966.png',
  'France': 'france-128x128-32967.png',
  'French Guiana': 'french-128x128-32975.png',
  'French Polynesia': 'french-128x128-32977.png',
  'Gabon': 'gabon-128x128-32968.png',
  'Gambia': 'gambie-128x128-32976.png',
  'Georgia': 'georgie-128x128-32979.png',
  'Germany': 'allemagne-128x128-32989.png',
  'Ghana': 'ghana-128x128-32990.png',
  'Gibraltar': 'gibraltar-128x128-32992.png',
  'Greece': 'grece-128x128-32991.png',
  'Grenada': 'grenade-128x128-33002.png',
  'Guadeloupe': 'guadeloupe-128x128-32982.png',
  'Guatemala': 'guatemala-128x128-33009.png',
  'Guinea': 'guinee-128x128-32983.png',
  'Guinea-Bissau': 'guinea-128x128-33008.png',
  'Guyana': 'guyana-128x128-33007.png',
  'Haiti': 'haiti-128x128-32984.png',
  'Honduras': 'honduras-128x128-33020.png',
  'Hong Kong': 'hong-kong-128x128-32987.png',
  'Hungary': 'hongrie-128x128-33019.png',
  'Iceland': 'islande-128x128-33152.png',
  'India': 'inde-128x128-32988.png',
  'Indonesia': 'indonesie-128x128-32994.png',
  'Iran': 'iran-128x128-33022.png',
  'Iraq': 'irak-128x128-33017.png',
  'Ireland': 'irlande-128x128-32996.png',
  'Israel': 'israel-128x128-32997.png',
  'Italy': 'italie-128x128-32999.png',
  'Jamaica': 'jamaique-128x128-33000.png',
  'Japan': 'japon-128x128-33001.png',
  'Jordan': 'jordanie-128x128-33005.png',
  'Kazakhstan': 'kazakhstan-128x128-33021.png',
  'Kenya': 'kenya-128x128-33010.png',
  'Kiribati': 'kiribati-128x128-33012.png',
  'Kuwait': 'koweit-128x128-33013.png',
  'Kyrgyzstan': 'kirghizistan-128x128-33014.png',
  'Laos': 'laos-128x128-33018.png',
  'Latvia': 'lettonie-128x128-33031.png',
  'Lebanon': 'liban-128x128-33015.png',
  'Lesotho': 'lesotho-128x128-33029.png',
  'Liberia': 'liberia-128x128-33032.png',
  'Libya': 'libye-128x128-33026.png',
  'Liechtenstein': 'liechtenstein-128x128-33016.png',
  'Lithuania': 'lituanie-128x128-33043.png',
  'Luxembourg': 'luxembourg-128x128-33041.png',
  'Madagascar': 'madagascar-128x128-33042.png',
  'Malawi': 'malawi-128x128-33116.png',
  'Malaysia': 'malaisie-128x128-33134.png',
  'Maldives': 'maldives-128x128-33122.png',
  'Mali': 'mali-128x128-33025.png',
  'Malta': 'malte-128x128-33120.png',
  'Marshall Islands': 'iles-marshall-128x128-33054.png',
  'Martinique': 'martinique-128x128-33119.png',
  'Mauritania': 'mauritanie-128x128-33125.png',
  'Mauritius': 'maurice-128x128-33121.png',
  'Mayotte': 'mayotte-128x128-33123.png',
  'Mexico': 'mexique-128x128-33133.png',
  'Micronesia': 'federated-128x128-32969.png',
  'Moldova': 'moldavie-128x128-33055.png',
  'Monaco': 'monaco-128x128-33053.png',
  'Mongolia':'mongolie-128x128-33127.png',
  'Montenegro': 'montenegro-128x128-33056.png',
  'Montserrat': 'montserrat-128x128-33126.png',
  'Morocco': 'maroc-128x128-33027.png',
  'Mozambique': 'mozambique-128x128-33033.png',
  'Myanmar': 'myanmar-128x128-33118.png',
  'Namibia': 'namibie-128x128-33132.png',
  'Nauru': 'nauru-128x128-33030.png',
  'Nepal': 'nepal-128x128-33028.png',
  'Netherlands': 'pays-bas-128x128-33035.png',
  'New Caledonia': 'new-128x128-33036.png',
  'New Zealand': 'nouvelle-zelande-128x128-33065.png',
  'Nicaragua': 'nicaragua-128x128-33037.png',
  'Niger': 'niger-128x128-33038.png',
  'Nigeria': 'nigeria-128x128-33039.png',
  'Niue': 'niue-128x128-33040.png',
  'North Korea': 'north-128x128-33045.png',
  'Norway': 'norvege-128x128-33155.png',
  'Oman': 'oman-128x128-33046.png',
  'Pakistan': 'pakistan-128x128-33047.png',
  'Palau': 'palau-128x128-33048.png',
  'Panama': 'panama-128x128-33049.png',
  'Papua New Guinea': 'papouasie-nouvelle-guinee-128x128-33050.png',
  'Paraguay': 'paraguay-128x128-33066.png',
  'Peru': 'perou-128x128-33051.png',
  'Philippines': 'philippines-128x128-33052.png',
  'Poland': 'pologne-128x128-33057.png',
  'Portugal': 'portugal-128x128-33058.png',
  'Puerto Rico': 'porto-rico-128x128-33059.png',
  'Qatar': 'qatar-128x128-33060.png',
  'Republic of the Congo': 'republic-128x128-33061.png',
  'Romania': 'roumanie-128x128-33063.png',
  'Russia': 'russie-128x128-33064.png',
  'Rwanda': 'rwanda-128x128-33067.png',
  'Saint Kitts and Nevis': 'saint-128x128-33068.png',
  'Saint Lucia': 'sainte-lucie-128x128-33069.png',
  'Saint Vincent and the Grenadines': 'saint-128x128-33070.png',
  'Samoa': 'samoa-128x128-33124.png',
  'San Marino': 'saint-marin-128x128-33074.png',
  'Sao Tome and Principe': 'sao-128x128-33075.png',
  'Saudi Arabia': 'arabie-saoudite-128x128-33076.png',
  'Senegal': 'senegal-128x128-33077.png',
  'Serbia': 'serbie-128x128-33099.png',
  'Seychelles': 'seychelles-128x128-33078.png',
  'Sierra Leone': 'sierra-leone-128x128-33079.png',
  'Singapore': 'singapour-128x128-33080.png',
  'Slovakia': 'slovaquie-128x128-33082.png',
  'Slovenia': 'slovenie-128x128-33084.png',
  'Solomon Islands': 'iles-salomon-128x128-33083.png',
  'Somalia': 'somalie-128x128-33085.png',
  'South Africa': 'afrique-du-sud-128x128-33130.png',
  'South Korea': 'coree-du-sud-128x128-33086.png',
  'South Sudan': 'south-128x128-33088.png',
  'Spain': 'espagne-128x128-33105.png',
  'Sri Lanka': 'sri-lanka-128x128-33091.png',
  'Sudan': 'soudan-128x128-33090.png',
  'Suriname': 'suriname-128x128-33092.png',
  'Swaziland': 'eswatini-128x128-33094.png',
  'Sweden': 'suede-128x128-33096.png',
  'Switzerland': 'suisse-128x128-33095.png',
  'Syrian Arab Republic': 'syrie-128x128-33097.png',
  'Taiwan': 'taiwan-128x128-33098.png',
  'Tajikistan': 'tadjikistan-128x128-33100.png',
  'Tanzania': 'tanzanie-128x128-33101.png',
  'Thailand': 'thailande-128x128-33102.png',
  'Timor-Leste': 'timor-128x128-33103.png',
  'Togo': 'togo-128x128-33106.png',
  'Tonga': 'tonga-128x128-33107.png',
  'Trinidad and Tobago': 'trinite-et-tobago-128x128-33108.png',
  'Tunisia': 'tunisie-128x128-33110.png',
  'Turkey': 'turquie-128x128-33109.png',
  'Turkmenistan': 'turkmenistan-128x128-33111.png',
  'Tuvalu': 'tuvalu-128x128-33113.png',
  'Uganda': 'ouganda-128x128-33129.png',
  'Ukraine': 'ukraine-128x128-33145.png',
  'United Arab Emirates': 'emirats-arabes-unis-128x128-33114.png',
  'United Kingdom': 'royaume-uni-128x128-33115.png',
  'United States': 'etats-unis-128x128-33135.png',
  'Uruguay': 'uruguay-128x128-33140.png',
  'Uzbekistan': 'ouzbekistan-128x128-33141.png',
  'Vanuatu': 'vanuatu-128x128-33142.png',
  'Venezuela': 'venezuela-128x128-33138.png',
  'Vietnam': 'vietnam-128x128-33148.png',
  'Virgin Islands, British': 'virgin-128x128-33147.png',
  'Virgin Islands, U.S.': 'virgin-128x128-33149.png',
  'Yemen': 'yemen-128x128-33143.png',
  'Zambia': 'zambie-128x128-33146.png',
  'Zimbabwe': 'zimbabwe-128x128-33150.png',
};

// Fonction pour obtenir le nom du fichier drapeau
export function getFlagImage(countryName: string): string | null {
  // Normaliser les pays avec accents français
  const normalized = normalizeFrenchCountryName(countryName);
  return COUNTRY_FLAG_MAP[normalized] || COUNTRY_FLAG_MAP[countryName] || null;
}

// Fonction pour normaliser les noms de pays français vers l'anglais
function normalizeFrenchCountryName(name: string): string {
  const frenchToEnglish: Record<string, string> = {
    'Afrique du Sud': 'South Africa',
    'Albanie':'Albania',
    'Algérie': 'Algeria',
    'Allemagne': 'Germany',
    'Arabie Saoudite': 'Saudi Arabia',
    'Argentine': 'Argentina',
    'Arménie': 'Armenia',
    'Australie': 'Australia',
    'Autriche': 'Austria',
    'Azerbaïdjan': 'Azerbaijan',
    'Bahreïn': 'Bahrain',
    'Bélarus': 'Belarus',
    'Barbade': 'Barbados',
    'Belgique': 'Belgium',
    'Bénin': 'Benin',
    'Birmanie': 'Myanmar',
    'Birmanie-Myanmar': 'Myanmar',
    'Bhoutan': 'Bhutan',
    'Bolivie': 'Bolivia',
    'Bosnie-Herzégovine': 'Bosnia and Herzegovina',
    'Botswana': 'Botswana',
    'Brésil': 'Brazil',
    'Bulgarie': 'Bulgaria',
    'Burkina Faso': 'Burkina Faso',
    'Cambodge': 'Cambodia',
    'Cameroun': 'Cameroon',
    'Canada': 'Canada',
    'Cap-Vert': 'Cabo Verde',
    'Chili': 'Chile',
    'Chine': 'China',
    'Chypre': 'Cyprus',
    'Colombie': 'Colombia',
    'Comores': 'Comoros',
    'Congo': 'Republic of the Congo',
    'Corée du Nord': 'North Korea',
    'Corée du Sud': 'South Korea',
    'Costa Rica': 'Costa Rica',
    'Côte d\'Ivoire': 'Cote d\'Ivoire',
    'Croatie': 'Croatia',
    'Cuba': 'Cuba',
    'Curaçao': 'Curacao',
    'D.R. Congo': 'Democratic Republic of the Congo',
    'Danemark': 'Denmark',
    'Djibouti': 'Djibouti',
    'Dominique': 'Dominica',
    'Égypte': 'Egypt',
    'Émirats Arabes Unis': 'United Arab Emirates',
    'Équateur': 'Ecuador',
    'Érythrée': 'Eritrea',
    'Espagne': 'Spain',
    'Estonie': 'Estonia',
    'États-Unis': 'United States',
    'Éthiopie': 'Ethiopia',
    'Fidji': 'Fiji',
    'Finlande': 'Finland',
    'France': 'France',
    'Gabon': 'Gabon',
    'Gambie': 'Gambia',
    'Géorgie': 'Georgia',
    'Ghana': 'Ghana',
    'Gibraltar': 'Gibraltar',
    'Grèce': 'Greece',
    'Grenade': 'Grenada',
    'Guadeloupe': 'Guadeloupe',
    'Guatemala': 'Guatemala',
    'Guinée': 'Guinea',
    'Guinée équatoriale': 'Equatorial Guinea',
    'Guinée-Bissau': 'Guinea-Bissau',
    'Guyana': 'Guyana',
    'Guyane': 'Guyana',
    'Guyane française': 'French Guiana',
    'Haïti': 'Haiti',
    'Honduras': 'Honduras',
    'Hong Kong': 'Hong Kong',
    'Hongrie': 'Hungary',
    'Îles Caïmans': 'Cayman Islands',
    'Inde': 'India',
    'Indonésie': 'Indonesia',
    'Irak': 'Iraq',
    'Iran': 'Iran',
    'Irlande': 'Ireland',
    'Islande': 'Iceland',
    'Israël': 'Israel',
    'Italie': 'Italy',
    'Jamaïque': 'Jamaica',
    'Japon': 'Japan',
    'Jordanie': 'Jordan',
    'Kazakhstan': 'Kazakhstan',
    'Kenya': 'Kenya',
    'République Kirghize': 'Kyrgyzstan',
    'Kiribati': 'Kiribati',
    'Koweït': 'Kuwait',
    'Laos': 'Laos',
    'Lesotho': 'Lesotho',
    'Lettonie': 'Latvia',
    'Liban': 'Lebanon',
    'Libéria': 'Liberia',
    'Libye': 'Libya',
    'Liechtenstein': 'Liechtenstein',
    'Lituanie': 'Lithuania',
    'Luxembourg': 'Luxembourg',
    'Madagascar': 'Madagascar',
    'Malaisie': 'Malaysia',
    'Malawi': 'Malawi',
    'Maldives': 'Maldives',
    'Mali': 'Mali',
    'Malte': 'Malta',
    'Maroc': 'Morocco',
    'Martinique': 'Martinique',
    'Mauritanie': 'Mauritania',
    'Maurice': 'Mauritius',
    'Mayotte': 'Mayotte',
    'Mexique': 'Mexico',
    'Micronésie': 'Micronesia',
    'La Moldavie': 'Moldova',
    'Monaco': 'Monaco',
    'Mongolie': 'Mongolia',
    'Monténégro': 'Montenegro',
    'Montserrat': 'Montserrat',
    'Mozambique': 'Mozambique',
    'Myanmar': 'Myanmar',
    'Namibie': 'Namibia',
    'Nauru': 'Nauru',
    'Népal': 'Nepal',
    'Nicaragua': 'Nicaragua',
    'Nigéria': 'Nigeria',
    'Niger': 'Niger',
    'Niue': 'Niue',
    'Norvège': 'Norway',
    'Nouvelle-Calédonie': 'New Caledonia',
    'Nouvelle-Zélande': 'New Zealand',
    'Oman': 'Oman',
    'Ouganda': 'Uganda',
    'Ouzbékistan': 'Uzbekistan',
    'Pakistan': 'Pakistan',
    'Palaos': 'Palau',
    'Panama': 'Panama',
    'Papouasie-Nouvelle-Guinée': 'Papua New Guinea',
    'Paraguay': 'Paraguay',
    'Pays-Bas': 'Netherlands',
    'Pérou': 'Peru',
    'Philippines': 'Philippines',
    'Pologne': 'Poland',
    'Polynésie française': 'French Polynesia',
    'Porto Rico': 'Puerto Rico',
    'Portugal': 'Portugal',
    'Qatar': 'Qatar',
    'République Centrafricaine': 'Central African Republic',
    'République Démocratique du Congo': 'Democratic Republic of the Congo',
    'République Dominicaine': 'Dominican Republic',
    'République Tchèque': 'Czech Republic',
    'Rép. Centrafricaine': 'Central African Republic',
    'Rép. Dominicaine': 'Dominican Republic',
    'Roumanie': 'Romania',
    'Royaume-Uni': 'United Kingdom',
    'Russie': 'Russia',
    'Rwanda': 'Rwanda',
    'Saint-Marin': 'San Marino',
    'Saint-Vincent-et-les-Grenadines': 'Saint Vincent and the Grenadines',
    'Sainte-Lucie': 'Saint Lucia',
    'Salvador': 'El Salvador',
    'Samoa': 'Samoa',
    'Samoa américaines': 'American Samoa',
    'Sao Tomé-et-Principe': 'Sao Tome and Principe',
    'Sénégal': 'Senegal',
    'Serbie': 'Serbia',
    'Seychelles': 'Seychelles',
    'Sierra Leone': 'Sierra Leone',
    'Singapour': 'Singapore',
    'Slovaquie': 'Slovakia',
    'Slovénie': 'Slovenia',
    'Somalie': 'Somalia',
    'Soudan': 'Sudan',
    'Soudan du Sud': 'South Sudan',
    'Sri Lanka': 'Sri Lanka',
    'Suède': 'Sweden',
    'Suisse': 'Switzerland',
    'Suriname': 'Suriname',
    'Swaziland': 'Swaziland',
    'Syrie': 'Syrian Arab Republic',
    'Tadjikistan': 'Tajikistan',
    'Taïwan': 'Taiwan',
    'Tanzanie': 'Tanzania',
    'Tchad': 'Chad',
    'Thaïlande': 'Thailand',
    'Timor oriental': 'Timor-Leste',
    'Timor-Leste': 'Timor-Leste',
    'Togo': 'Togo',
    'Tonga': 'Tonga',
    'Trinité-et-Tobago': 'Trinidad and Tobago',
    'Trinité et Tobago': 'Trinidad and Tobago',
    'Tunisie': 'Tunisia',
    'Turkménistan': 'Turkmenistan',
    'Turquie': 'Turkey',
    'Tuvalu': 'Tuvalu',
    'Ukraine': 'Ukraine',
    'Uruguay': 'Uruguay',
    'USA': 'United States',
    'Vanuatu': 'Vanuatu',
    'Venezuela': 'Venezuela',
    'Viet Nam': 'Vietnam',
    'Vietnam': 'Vietnam',
    'Yémen': 'Yemen',
    'Zambie': 'Zambia',
    'Zimbabwe': 'Zimbabwe',
  };

  return frenchToEnglish[name] || name;
}

// Mapping pour corriger les noms de fichiers avec accents vers les noms actuels en base
const FLAG_FILE_FIXES: Record<string, string> = {
  'algérie-128x128-32972.png': 'algerie-128x128-32972.png',
  'australie-128x128-32912': 'austallia-128x128-32912.png',
 ' autriche-128x128-32920.png': 'austria-128x128-32920.png',
};

// Fonction pour obtenir l'URL complète du drapeau
export function getFlagUrl(countryName: string): string | null {
  let flagFile = getFlagImage(countryName);
  // Corriger les noms de fichiers avec accents vers les fichiers réels
  if (flagFile && FLAG_FILE_FIXES[flagFile]) {
    flagFile = FLAG_FILE_FIXES[flagFile];
  }
  return flagFile ? `/flags/${flagFile}` : null;
}

// Fonction de fallback vers emoji si pas de drapeau
export function getFlagEmoji(code: string): string {
  if (!code || code.length !== 2) return '🌐';
  const cp1 = code.toUpperCase().charCodeAt(0) - 65 + 0x1F1E6;
  const cp2 = code.toUpperCase().charCodeAt(1) - 65 + 0x1F1E6;
  return String.fromCodePoint(cp1) + String.fromCodePoint(cp2);
}